[project]
name = "rag-agent"
version = "0.1.0"
description = ""
authors = [
    {name = "sean22-blip",email = "iseandxd@gmail.com"}
]
requires-python = ">=3.10,<4.0"
dependencies = [
    "uagents (>=0.25.5,<0.26.0)"
]

[tool.poetry]
package-mode = false

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"